### ISSUE TITLE
Command fails on non-ascii input

### ISSUE THREAD

**Issue by urschrei** [Mitranim/sublime-rust-fmt#1]
How to reproduce: include a non-ascii character in your source file. Error:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
        return self.run(edit)
      File "RustFmt in /Users/sth/Dropbox/Sublime Text 3/Installed Packages/RustFmt.sublime-package", line 80, in run
      File "RustFmt in /Users/sth/Dropbox/Sublime Text 3/Installed Packages/RustFmt.sublime-package", line 46, in run_format
      File "./python3.3/subprocess.py", line 920, in communicate
        if _mswindows:
      File "./python3.3/subprocess.py", line 1556, in _communicate
        elif _WIFEXITED(sts):
      File "./python3.3/subprocess.py", line 1629, in _communicate_with_poll
        while True:
      File "./python3.3/subprocess.py", line 1590, in _save_input
        # can't get the status.
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2728' in position 3909: ordinal not in range(128)

**Comment by mitranim** [comment]
Good catch. Just pushed a fix. Please update the plugin and try again.

**Comment by urschrei** [comment]
Working now. Thank you!
